version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    hostname: clickhouse
    restart: unless-stopped
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_ADMIN_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_ADMIN_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "${CLICKHOUSE_HTTP_PORT:-8123}:8123" 
      - "${CLICKHOUSE_TCP_PORT:-9000}:9000" 
    volumes:
      - clickhouse-data:/var/lib/clickhouse

volumes:
  clickhouse-data:

